# ---------------------------------------------------------------
# Workflow File : build-on-macOS.yml
# File Authors  :  Aoran Zeng <ccmywish@qq.com>
# Contributors  :   Nul None  <nul@none.org>
#               |
# Created On    : <2023-09-15>
# Last Modified : <2025-06-16>
#
# Build chsrc on macOS and upload it to GitHub: the 'pre' release
# ---------------------------------------------------------------

name: Build on macOS
on:
  push:
    branches: [ "gh-build" ]
  pull_request:
    branches: [ "gh-build" ]

jobs:
  build-and-upload-on-M1:
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build for AArch64
      run: |
        make CI CI_ARTIFACT_NAME=chsrc-aarch64-macos

    - name: List files
      run: ls *-macos

    - name: Upload
      uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: pre
        files: |
          chsrc-aarch64-macos
        token: ${{ secrets.UPLOAD_TO_GITHUB }}


  build-and-upload-on-x64:
    runs-on: macos-13 # macos-14 is AArch64(ARMv8-A)

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build for x64
      run: |
        make CI CI_ARTIFACT_NAME=chsrc-x64-macos

    - name: List files
      run: ls *-macos

    - name: Upload
      uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: pre
        files: |
          chsrc-x64-macos
        token: ${{ secrets.UPLOAD_TO_GITHUB }}
